In [1]:
import pandas as pd

In [2]:
#SERIES
data=[1,2,3,4,5]
series = pd.Series(data)

In [3]:
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
#create a series dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)

In [7]:
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [8]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index)

a    10
b    20
c    30
dtype: int64

In [9]:
#DataFrame

data={
    'Name':['Darshan','Jay','Krish'],
    'Age':[25,34,23],
    'City':['Delhi','Mumbai','Chennai']
}

In [10]:
data=pd.DataFrame(data)

In [11]:
print(data)

      Name  Age     City
0  Darshan   25    Delhi
1      Jay   34   Mumbai
2    Krish   23  Chennai

In [12]:
type(data)

pandas.core.frame.DataFrame

In [13]:
import numpy as np
np.array(data)

array([['Darshan', 25, 'Delhi'],
       ['Jay', 34, 'Mumbai'],
       ['Krish', 23, 'Chennai']], dtype=object)

In [26]:
#Create a dataframe from the list of dictonaries


data=[
        {'Name':'Darshan', 'Age':23 , 'City':'Delhi'},
        {'Name':'Darshan', 'Age':23 , 'City':'Delhi'},
        {'Name':'Darshan', 'Age':23 , 'City':'Delhi'},
        {'Name':'Darshan', 'Age':23 , 'City':'Delhi'},
        {'Name':'Darshan', 'Age':23 , 'City':'Delhi'}
]


df1=pd.DataFrame(data)
df1

      Name  Age   City
0  Darshan   23  Delhi
1  Darshan   23  Delhi
2  Darshan   23  Delhi
3  Darshan   23  Delhi
4  Darshan   23  Delhi

In [20]:
df=pd.read_csv(r"C:\Users\PINKY\OneDrive\Desktop\python\1_Python_basics\Churn_Modelling.csv")

In [21]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [23]:
df.iloc[0]          #accessing the row of ith number

RowNumber                  1
CustomerId          15634602
Surname             Hargrave
CreditScore              619
Geography             France
Gender                Female
Age                       42
Tenure                     2
Balance                  0.0
NumOfProducts              1
HasCrCard                  1
IsActiveMember             1
EstimatedSalary    101348.88
Exited                     1
Name: 0, dtype: object

In [24]:
#Accessing the specific element

df.at[2,'Geography']

'France'

In [25]:
#Accessing specify index using row and column index


df.iat[2,4]

'France'

In [29]:
#Data manipulation

#add a new column

df1['Salary']=[5000090,2023023,2342777,3322000,2324000]

In [30]:
df1

      Name  Age   City   Salary
0  Darshan   23  Delhi  5000090
1  Darshan   23  Delhi  2023023
2  Darshan   23  Delhi  2342777
3  Darshan   23  Delhi  3322000
4  Darshan   23  Delhi  2324000

In [33]:
df1.drop('Salary',axis=1,inplace=True)

In [34]:
df1

      Name  Age   City
0  Darshan   23  Delhi
1  Darshan   23  Delhi
2  Darshan   23  Delhi
3  Darshan   23  Delhi
4  Darshan   23  Delhi

In [35]:
#ADD age + 1


df1['Age']=df1['Age']+1

In [36]:
df1

      Name  Age   City
0  Darshan   24  Delhi
1  Darshan   24  Delhi
2  Darshan   24  Delhi
3  Darshan   24  Delhi
4  Darshan   24  Delhi